### ISSUE TITLE
FoaRTT: incorrect (undesired) order of rotations

### ISSUE THREAD

**Issue by totalgee** [ambisonictoolkit/atk-sc3#86]
Hi there, this is maybe something that just needs clarifying (to me). I've been playing with both SC-HOA and ATK, and comparing them to try to understand some things. I had problems with order of rotations in SC-HOA, and went back to compare with ATK to see if it was the same or different. (answer: the same; equally confusing ;-)

> First, I'm aware (according to the docs?) that the channel order is different for these two. The ATK documentation says the order of channels is w,x,y,z, and that +X is forward, +Y is left, and +Z is up. In SC-HOA, the channel order -- for first-order ambisonic -- is w,y,z,x, but the axes have the same meaning: +X forward, +Y left, +Z up. (This is just a note, to say I think I've been correctly comparing X to X, with appropriate shuffling of the indices. There is a difference in normalization, but this is not important to illustrate my point.)

If I do a `FoaPush.ar(FoaEncode.ar(DC.ar(1), FoaEncoderMatrix.newOmni), 0.5pi, 0, 0)` I get the XYZ vector `[1,0,0]`, as expected, i.e. "in front".

One thing that really confused me were the terms "tumble" and "tilt", which to my intuition seemed (and still seem) reversed -- although now I see they are [often used this way](http://www.blueripplesound.com/rotations) with ambisonics. From graphics I'm used to the terms "pitch" and "roll".  I suppose my confusion arises because I think: "tilt forward or backward"; and "tumble" makes me think of the clockwise rotation of a front-loading "tumble drier". Anyhow, now I see this is just a matter of terminology/convention, and not a bug... (-;

But, what seems not to be as useful to me, is the order of composition of rotations for `FoaRTT` (for the record, I have the same issue with SC-HOA's method `HOATransRotateXYZ`). For me, this function would be useful if the roll (tilt) were applied first, then pitch (tumble), then heading (rotation/azimuth). This is the convention in computer graphics, for example things like flight simulators, etc. (when quaternions aren't used to eliminate the potential gimble lock when using Euler angles) -- although we say "heading/pitch/roll", the order of rotation application is the reverse...the heading is "most important" so it is applied last. This convention is very useful, because a quick look at the heading (rotation) gives you a good idea of the overall "compass direction" you're looking, the pitch (tumble) gives you an idea if you're looking up or down, and the roll (tilt) tells you if you've rotated your view along that overall viewing direction. But when they compose in the reverse order (as in `FoaRTT` or `HOATransRotateXYZ`), you lose any sense of meaning in those three numbers (at least I do!).

Am I missing something? Is there a reason or use case why the opposite rotation order was chosen? (Anyhow, I know at least I can compose whatever order I like by using the methods `FoaTilt`, `FoaTumble`, `FoaRotate`.)

Here's an example of how I'd like it to work:
```supercollider
(
Ndef(\ambiDebug, {
	var foa = FoaPush.ar(FoaEncode.ar(DC.ar(1), FoaEncoderMatrix.newOmni), 0.5pi, 30.degrad, 0);
	// Initial sound source is [0.866, 0.5, 0], i.e. mostly forward (30 degrees to the left)

	var roll = 90.degrad; // roll it ninety degrees clockwise, so it's now 30 degrees up
	var pitch = -60.degrad; // pitch it down 60 degrees, so it's 30 degrees down
	var yaw = -90.degrad; // rotate it 90 degrees right, so it's to the right, 30 degrees down

	// FoaRTT does the rotations backward, compared to what I'd want...
	// foa = FoaRTT.ar(foa, rotAngle: yaw, tilAngle: roll, tumAngle: pitch);
	
	// This is the order I would like for composed rotations:
	foa = FoaTilt.ar(foa, roll);
	foa = FoaTumble.ar(foa, pitch);
	foa = FoaRotate.ar(foa, yaw);

	foa[1..3].round(1e-6).poll(1, [\X_fwd, \Y_left, \Z_up]);
	// [0, -0.866, -0.5], i.e. mostly right (30 degrees down)
	foa
})
)
```

P.S. My other question is why the tumble angle is reversed in sign from what the right-hand rule would indicate. Roll/tilt is correctly clockwise around the forward/X axis, heading/rotation is correctly "to the left" around the up/Z axis, but pitch/tumble is about the negated left/Y axis. (I guess this is just because conceptually it's nicer to think of positive numbers rotating upwards, so it's okay...just some thing to document and be aware of.)

Thanks for helping me clarify my confusion.

**Comment by joslloand** [comment]
Hello @totalgee,

This isn't really a bug, or anything that is "incorrect" given the conventions of Ambisonics, so I'm going to close this as an issue.

Agreed, if you're coming from the world of navigation or computer graphics the conventions are potentially confusing. The rotation convention(s) for Ambisonics:

**Rotate**: translate +X to +Y
**Tilt**: translate +Y to +Z
**Tumble**: translate +X to +Z

Also, I think some of the confusion arises as to whether a cascade of rotations is _extrinsic_ or _intrinsic_. With Ambisonics, the axial system stays fixed "to the world".

**Rotate-Tilt-Tumble** (**RTT**) is **Rotate** followed by **Tilt** followed by **Tumble**. To undo this transform you would **Tumble** followed by **Tilt** followed by **Tumble**, negating each rotation angle.

For ATK-HOA (SuperCollider) we're including **Yaw-Pitch-Roll** (**YPR**), because of its use in navigation.

**RTT** is a compound _extrinsic_ rotation. **YPR** is a compound mixed _intrinsic/extrinsic_. Here's a code fragment (from ATK-HOA: HoaYPR) to implement **YPR** via **Rotate** and axis swaps:

```
// Note reversed order of rotations to achieve intrinsic YPR
mK = this.getJKMatrix(\k, n);    // "K" matrix: swap Z<>X axes
mJ = this.getJKMatrix(\j, n);    // "J" matrix: swap Z<>Y axes
mJK = this.getJKMatrix(\jk, n);  // combine (J * K)

// roll (tilt) : K -> Z(tilt) ->
hoa = HoaUGen.mixMatrix(in, mK);
hoa = HoaRotate.ar(hoa, roll.neg, n); // roll.neg: see note in HoaTilt

// combine (J * K)
hoa = HoaUGen.mixMatrix(hoa, mJK);

// pitch (tumble) : -> Z(tumble) -> J
hoa = HoaRotate.ar(hoa, pitch, n);
hoa = HoaUGen.mixMatrix(hoa, mJ);

// yaw (rotate)
^HoaRotate.ar(hoa, yaw, n);
```

The good news: this is coming in the ATK-HOA implementation. If you'd like to play around with it, you can pull down the [sandbox version](https://github.com/ambisonictoolkit/atk-sc3/tree/sandbox/hoa). There are still some under the hood changes and optimizations to be made before a full release, and more verbose documentation to be added. The top level interfaces are intended to remain the same.

**Comment by totalgee** [comment]
Thanks for the detailed reply! I look forward to trying the ATK-HOA version when it's released (and maybe before, if I find time). I'm happy to see you've got these "aliases" there... (-;

```supercollider
HoaYaw : HoaRotate { }
HoaPitch : HoaTumble { }
HoaRoll : HoaTilt { }
```

**Comment by joslloand** [comment]
@totalgee these synonyms apply only if as single transform is applied. For **YPR** as a cascade the above algorithm is the way to go.
